feedback/urls.py
#from django.contrib import admin
from . import views
from django.urls import path, include

app_name = 'feedback'

urlpatterns = [
    path('', views.feedback, name='feedback'),
    path('add-feedback', views.add_feedback, name='add_feedback'),
    path('delete-feedback/<int:id>', views.delete_feedback, name='delete_feedback'),
]

tk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('donation/', include('donation.urls')),
    path('covcase/', include('covcase.urls')),
    path('feedback/', include('feedback.urls')),
    path('FAQ/', include('FAQapp.urls')),
    path('artikel/', include('artikel.urls')),
]

feedback/models.py
from django.db import models

# Create your models here.

class Feedback(models.Model):
	name = models.CharField(max_length=200)
	email = models.CharField(max_length=200)
	message = models.TextField()

	def __str__(self):
		return "{} - {} - {}".format(self.name, self.email, self.message)

feedback/forms.py
from django.shortcuts import render, redirect
from django import forms
from .models import Feedback 
#from . import forms
from django.forms import ModelForm
# from . import models

class CreateFeedbackForm(forms.ModelForm):
	class Meta:
		model = Feedback 
		fields = [
			"name",
			"email",
			"message",
		]

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.Meta.fields:
			self.fields[field].widget.attrs.update({
				'class': 'form-control',
			})

feedback/views.py
from django.shortcuts import render, redirect
from .forms import CreateFeedbackForm
from .models import Feedback
from . import forms

# Create your views here.
def home(request):
    return render(request, 'main/home.html')

def feedback(request):
	feedback = Feedback.objects.all()
	response = {
		'title' : 'Feedback',
        'feedback': feedback,
	}
	return render(request, 'feedback_page.html', response)

def add_feedback(request):
    response = {
        'title' : 'Add Feedback',
        'feedback_form': CreateFeedbackForm()
    }

    if request.method == "POST":
        feedback_form = CreateFeedbackForm(request.POST)
        if feedback_form.is_valid():
            feedback_form.save()
            return redirect('feedback:feedback')
    return render(request, 'add_feedback_page.html', response)

def delete_feedback(request, id):
    feedback = Feedback.objects.get(id=id)
    feedback.delete()
    return redirect('feedback:feedback')

feedback/templates/add_feedback_page.html
{% extends 'base_layout.html' %} 
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style_add_feedback.css' %}">
{% endblock %}

{% block content %}
<div class="course">
    <div style="display: flex; justify-content: left; padding-top: 1rem; padding-left: 1rem;"><button><a href="{% url 'feedback:feedback' %}">See all the feedback!</a></button></div>
    <div class="wrap-course">
        <h1 style="color: #004850; font-size: 33px; font-family: Roboto;"><b>Form Feedback FightCov-19</b></h1>
        <div class="wrap">
            <form action="{% url 'feedback:add_feedback' %}" method="POST">
                {% csrf_token %}
                {% for field in feedback_form.visible_fields %}
                <div class="form-group">
                    <div class="col-sm-6 offset-sm-3">
                        <h5>{{field.label_tag}} {{field}}</h5>
                    </div>
                </div>
                {% endfor %}
                <div style="display: flex; justify-content: center; text-align: center"><button type="submit">Submit</button></div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

feedback/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block css %}
    {% endblock %}
    <title>{{ title }}</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <h4 style="color: #5AE2FC;"><b>Fight</b></h4><h4 style="color: black;"><b>Cov-19</b></h4>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link px-2" href="/"><b>Home</b></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link px-2" href="/covcase/"><b>Covid Cases</b></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link px-2" href="/donation/"><b>Donation</b></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link px-2" href="/artikel/"><b>Article</b></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link px-2" href="/FAQ/"><b>FAQ</b></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link px-2" href="/feedback/"><b>Feedback</b></a>
            </li>
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

feedback/templates/feedback_page.html
{% extends 'base_layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/style_feedback.css' %}">
{% endblock %}

{% block content %}
<div class="feedback">
    <div class="wrap">
        {% if feedback.count %}
        <h1 style="text-align: center; font-size: 31px; color: #004850; font-family: Roboto;"><b>Thank you for visiting our website!</b></br><b>We really appreciate your feedback :)</b></h1>
        <button><a href="{% url 'feedback:add_feedback' %}">Write your feedback!</a></button>

        <div class="flex-wrap">
        {% for feedback_content in feedback %}
	        <div class="card">
	        	<div class="name">
	            	<h4 style="text-align: center;">{{ feedback_content.name }}</h4>
	        	</div>
	        	<div class="email">
	        		<h6 style="text-align: center;">{{ feedback_content.email }}</h6>
	        	</div>
	            <a href="{% url 'feedback:delete_feedback' id=feedback_content.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
	            <div class="card-message">
	            	<h5 style="text-align: center; font-size: 15px;">{{ feedback_content.message }}</h5>
	            </div>
	        </div>

        {% endfor %}
    	</div>
        {% else %}

        <div class="else"><body style="background-color: #D6F8FE">
        	<div class="text">
	            <h4><b style="color: #202546; font-size: 35px;">We need your feedback :)</b></h4>
	            <button><a href="{% url 'feedback:add_feedback' %}">Write here!</a></button>
	        </div>
        </div></body>

        {% endif %}
    </div>
 </div>

 <script>
	$(function() {
		var len_fit_name = 19;

		$('.name h4').each(function(i, obj) {
			var name = $(this)
			
			var len_item_name = name.html().length;
			if(len_fit_name < len_item_name) {
	    		var size_now = parseInt(name.css("font-size"));
	    		var size_new = size_now * len_fit_name/len_item_name;
	    		name.css("font-size",size_new);
			}
		})

		var len_fit_email = 30;

		$('.email h6').each(function(i, obj) {
			var email = $(this)
			
			var len_item_email = email.html().length;
			if(len_fit_email < len_item_email) {
	    		var size_now = parseInt(email.css("font-size"));
	    		var size_new = size_now * len_fit_email/len_item_email;
	    		email.css("font-size",size_new);
			}
		})
    });

 </script>

{% endblock %} 